spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: Deft201902619@
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        database: mysql
        database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        logging:
          level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE